### PR TITLE
Add scroll to table + remove sticky

### PR DESCRIPTION
**Pull request by nicolaskempf57**
Close https://github.com/etalab/data.gouv.fr/issues/958

### CODE REVIEW

**Comment by nicolaskempf57** [comment]
> I'm not sure I have the expected scrolls showing on Firefox. I have two vertical scroll bars in Chrome only one in Firefox. The horizontal scroll bar doesn't show consistently.

Indeed, you should have 2 scroll bars, one for the screen and the other for the table. The first one, should be at the end of the page for the horizontal scrollbar to show. This is what I reproduce on Firefox too

**Comment by maudetes** [comment]
A capture of what I experience. I think that the two vertical scroll bars overlap, leading to this behaviour.

[Uploading Capture d’écran vidéo de 06-01-2023 16:10:52.webm…]()

**Comment by nicolaskempf57** [comment]
Do we want to investigate this further or do we wait for https://github.com/etalab/csvapi-front/pull/113 to see if it fixes it ?

**Comment by maudetes** [comment]
> Do we want to investigate this further or do we wait for #113 to see if it fixes it ?

Let's wait and see the behavior on #113

**Comment by geoffreyaldebert** [comment]
@nicolaskempf57 I close this for now because we changed our main branches but if this is important do not hesitate to reopen it.

**Pull request closed without merging**
